name: Build & Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.7.0'
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Build Core
        run: |
          cd core
          npm ci
      - name: Serverless Stack Install
        run: |
          cd backend
          npm ci
      - name: Serverless Stack Deploy
        run: |
          cd backend
          npm run deploy -- --stage production
        env:
          NODE_OPTIONS: --max_old_space_size=8192
          AUTH0_AUDIENCE: ${{secrets.AUTH0_AUDIENCE}}
          AUTH0_DOMAIN: ${{secrets.AUTH0_DOMAIN}}
          AWS_ACCOUNT_ID: ${{secrets.AWS_ACCOUNT_ID}}
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
      - name: Build React App
        run: |
          cd app
          npm install
          CI=false npm run build
        env:
          REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}
          REACT_APP_REGION: ${{ secrets.REACT_APP_REGION }}
          REACT_APP_IDENTITY_POOL_ID: ${{ secrets.REACT_APP_IDENTITY_POOL_ID }}
          REACT_APP_USER_POOL_CLIENT_ID: ${{ secrets.REACT_APP_USER_POOL_CLIENT_ID }}
          REACT_APP_USER_POOL_ID: ${{ secrets.REACT_APP_USER_POOL_ID }}
          REACT_APP_IMAGE_BUCKET: ${{ secrets.REACT_APP_IMAGE_BUCKET }}
      - name: Deploy app build to S3 bucket
        run: |
          cd app
          aws s3 sync ./build/ s3://garagebloc.com --delete
